version: '3.8'
services:
  database:
    image: mariadb
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db-planning
      MYSQL_USER: mysql-database
      MYSQL_PASSWORD: password
volumes:
  dbdata: